// src/routes/settings/+page.svelte
<script lang="ts">
  import { settings } from '$lib/stores/settings';
  import Textarea from '$lib/components/textarea.svelte';
</script>

<div class="h-full p-4">
  <Textarea
    bind:value={$settings.token}
    label="Token"
    class="h-36"
    labelClass="text-secondary-foreground/70"
  />
</div>

// src/views/settings/index.vue
<script setup lang="ts">
import { Textarea } from '@tb-dev/vue';
import { useSettingsStore } from '@/stores/settings';

const settings = useSettingsStore();
</script>

<template>
  <div class="size-full p-4">
    <Textarea
      v-model.trim="settings.token"
      label="Token"
      label-class="text-secondary-foreground/70 h-36"
    />
  </div>
</template>
