// src/routes/history/+page.svelte
<script lang="ts">
  import { onError } from '$lib/utils';
  import { history } from '$lib/stores/history';
  import * as Card from '$lib/components/ui/card';
  import { Button } from '$lib/components/ui/button';
  import { writeText } from '@tauri-apps/plugin-clipboard-manager';

  function date(time: number) {
    return new Date(time).toLocaleString();
  }

  function copy(text: string) {
    writeText(text).catch(onError);
  }

  function remove(time: number) {
    $history.answers = $history.answers.filter((answer) => answer.date !== time);
  }
</script>

<div class="h-screen overflow-y-auto overflow-x-hidden p-4">
  <div class="space-y-2">
    {#each $history.answers as answer (answer.date)}
      <Card.Root>
        <Card.Header class="px-4 pb-2 pt-4">
          <Card.Title>{date(answer.date)}</Card.Title>
        </Card.Header>
        <Card.Content class="px-4 py-2">
          <p>{answer.text}</p>
        </Card.Content>
        <Card.Footer class="flex items-center justify-end gap-4 px-4 pb-4 pt-2">
          <Button size="sm" onclick={() => copy(answer.text)}>Copy</Button>
          <Button variant="destructive" size="sm" onclick={() => remove(answer.date)}>
            Remove
          </Button>
        </Card.Footer>
      </Card.Root>
    {/each}
  </div>
</div>

// src/views/history/index.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import { onError } from '@/lib/utils';
import { useHistoryStore } from '@/stores/history';
import { Button, Card } from '@tb-dev/vue-components';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';

const historyStore = useHistoryStore();
const { answers } = storeToRefs(historyStore);

function date(time: number) {
  return new Date(time).toLocaleString();
}

function copy(text: string) {
  writeText(text).catch(onError);
}

function remove(time: number) {
  answers.value = answers.value.filter((answer) => answer.date !== time);
}
</script>

<template>
  <div class="h-screen overflow-x-hidden overflow-y-auto p-4">
    <div class="space-y-2">
      <Card
        v-for="answer of answers"
        :key="answer.date"
        :title="date(answer.date)"
        class="p-0"
        header-class="px-4 pb-2 pt-4"
        content-class="px-4 py-2"
        footer-class="px-0"
      >
        <template #footer>
          <div class="flex w-full items-center justify-end gap-4 px-4 pt-2 pb-4">
            <Button size="sm" @click="() => copy(answer.text)">Copy</Button>
            <Button variant="destructive" size="sm" @click="() => remove(answer.date)">
              Remove
            </Button>
          </div>
        </template>

        <p>{{ answer.text }}</p>
      </Card>
    </div>
  </div>
</template>
